repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language: python
        stages: [ commit ]
        types: [ python ]
        args: ['--skip-string-normalization', '--preview']
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        stages: [ commit ]
        args: [ "--profile", "black", "--filter-files" ]
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        exclude: migrations
        stages: [ commit ]
  - repo: http://github.com/pycqa/bandit
    rev: "1.6.2"
    hooks:
      - id: bandit
        exclude: test
        stages: [ commit ]
  - repo: local
    hooks:
      - id: pre-commit-django-migrations
        name: Check Django migrations
        entry: python manage.py makemigrations --check
        stages: [ commit, push ]
        always_run: true
        language: system
        types: [ python ]
        pass_filenames: false
