# Generated by Django 2.2.11 on 2020-03-30 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('cambio', models.FloatField(verbose_name='cambio')),
                ('moneda', models.CharField(choices=[('USD', 'Dólares Americanos')], default='USD', max_length=3, verbose_name='moneda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cambio',
                'verbose_name_plural': 'Cambios',
                'ordering': ('-fecha',),
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('banco_cta_cte', 'Cuenta Corriente'), ('banco_caja_ahorro', 'Caja de Ahorro'), ('giro', 'Giro bancario')], max_length=50, verbose_name='tipo')),
                ('nro', models.CharField(max_length=50, verbose_name='Cuenta Nro.')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'ordering': ('entidad',),
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=254, verbose_name='nombre')),
                ('info_extra', models.TextField(blank=True, default='', verbose_name='Información Adicional')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
                ('nro_comprobante', models.CharField(max_length=50, verbose_name='Comprobante Nro.')),
                ('recibo_nro', models.IntegerField(verbose_name='Recibo de Donación Nro.')),
                ('monto_pyg', models.FloatField(blank=True, null=True, verbose_name='Monto Gs.')),
                ('monto_usd', models.FloatField(blank=True, null=True, verbose_name='Monto USD')),
                ('es_anonimo', models.BooleanField(default=False, verbose_name='Publicar como donación anónima')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='core.Cuenta', verbose_name='cuenta')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Entidad', verbose_name='origen')),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'ordering': ('-fecha',),
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos', verbose_name='Archivo')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.AddField(
            model_name='cuenta',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Entidad', verbose_name='Entidad'),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
                ('tipo_comprobante', models.IntegerField(choices=[(1, 'Factura'), (2, 'Recibo Legal')], verbose_name='Tipo de Comprobante')),
                ('nro_timbrado', models.IntegerField(blank=True, null=True, verbose_name='Timbrado Nro.')),
                ('nro_comprobante', models.CharField(max_length=50, verbose_name='Comprobante Nro.')),
                ('nro_op', models.CharField(max_length=50, verbose_name='O.P. Nro.')),
                ('concepto', models.CharField(max_length=254, verbose_name='Concepto')),
                ('cantidad', models.FloatField(verbose_name='Cantidad')),
                ('precio_unidad_pyg', models.FloatField(verbose_name='Precio unitario Gs.')),
                ('precio_total_pyg', models.FloatField(verbose_name='Precio total Gs.')),
                ('precio_unidad_usd', models.FloatField(verbose_name='Precio unitario USD.')),
                ('precio_total_usd', models.FloatField(verbose_name='Precio total USD.')),
                ('recepcion_donacion', models.CharField(help_text='Quién recibió la donación', max_length=254, verbose_name='Recepción de la Donación')),
                ('beneficiario', models.ForeignKey(help_text='A qué establecimiento se entregó la donación', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Entidad', verbose_name='Institución Beneficiada')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Entidad', verbose_name='Proveedor/Oferente')),
            ],
            options={
                'verbose_name': 'Compra/Destino de la donación',
                'verbose_name_plural': 'Compras/Destino de las donaciones',
                'ordering': ('-fecha',),
            },
        ),
    ]
