# Generated by Django 2.2.12 on 2020-04-03 03:32

from django.db import migrations


def crear_tipo_cuenta(apps, schema_editor):
    TipoCuenta = apps.get_model('core', 'TipoCuenta')
    tipos_cuenta = ('Cuenta Corriente', 'Caja de Ahorro', 'Billetera Móvil')
    for tipo in tipos_cuenta:
        TipoCuenta.objects.create(nombre=tipo)


def crear_tipo_comprobantes(apps, schema_editor):
    TipoComprobante = apps.get_model('core', 'TipoComprobante')
    tipos_comprobante = ('Factura', 'Recibo Legal', 'Documento de Aduanas')
    for tipo in tipos_comprobante:
        TipoComprobante.objects.create(nombre=tipo)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_tipo_cuenta, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(crear_tipo_comprobantes, reverse_code=migrations.RunPython.noop)
    ]
