# Generated by Django 2.2.11 on 2020-03-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200330_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='precio_total_pyg',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio total Gs.'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='precio_total_usd',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio total USD.'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='precio_unidad_pyg',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio unitario Gs.'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='precio_unidad_usd',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio unitario USD.'),
        ),
    ]
