# Generated by Django 2.2.12 on 2020-04-03 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200402_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto',
            name='medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utils.UnidadMedida', verbose_name='Unidad de Medida'),
        ),
    ]
