# Generated by Django 2.2.12 on 2020-04-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200404_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='_monto_pyg',
            field=models.FloatField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concepto',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Detalles del objeto: Para qué sirve, dónde se usa, etc.', verbose_name='Descripción'),
        ),
    ]
