# Generated by Django 2.2.12 on 2020-04-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200408_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompra',
            name='_precio_total_pyg',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='_precio_unitario_pyg',
            field=models.FloatField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
