# Generated by Django 2.2.12 on 2020-04-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200408_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donacion',
            old_name='_monto_pyg',
            new_name='monto_pyg',
        ),
        migrations.RenameField(
            model_name='itemcompra',
            old_name='_precio_unitario_pyg',
            new_name='precio_total_pyg',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='nro_orden_pago',
        ),
        migrations.RemoveField(
            model_name='itemcompra',
            name='_precio_total_pyg',
        ),
        migrations.AddField(
            model_name='compra',
            name='nro_cheque',
            field=models.CharField(default=0, max_length=50, verbose_name='Cheque Nro.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entidad',
            name='ruc',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='RUC'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='tipo_entidad',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Individuo'), (2, 'Empresa')], default=1, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='precio_unitario_pyg',
            field=models.FloatField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
