# Generated by Django 2.2.12 on 2020-04-15 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200409_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Entidad', verbose_name='Entidad Beneficiada')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
            },
        ),
        migrations.CreateModel(
            name='ItemEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(verbose_name='Cantidad')),
                ('recibido_por', models.CharField(max_length=250, verbose_name='Recibido por')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Concepto', verbose_name='Concepto')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_entregados', to='core.Entrega', verbose_name='Entrega')),
            ],
            options={
                'verbose_name': 'Item Entregado',
                'verbose_name_plural': 'Items Entregados',
            },
        ),
    ]
