# Generated by Django 2.2.12 on 2020-04-15 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_entrega_itementrega'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ('-fecha',), 'verbose_name': 'Adquisición Realizada', 'verbose_name_plural': 'Adquisiciones Realizadas'},
        ),
    ]
