# Generated by Django 2.2.12 on 2020-04-03 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo_iso', models.CharField(max_length=3, unique=True, verbose_name='Código ISO')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Escribir en Plural. Ej.: Kilogramos.', max_length=100, verbose_name='Nombre')),
                ('abreviacion', models.CharField(help_text='Ej.: Kg. para Kilogramos.', max_length=10, verbose_name='Abreviación')),
                ('cant_unidad_elemental', models.FloatField(blank=True, help_text='Para una caja de 100 items, escribir 100.', null=True, verbose_name='Cantidad en Unidad Elemental')),
                ('acepta_decimales', models.BooleanField(default=False, verbose_name='Acepta valores con coma')),
                ('unidad_elemental', models.ForeignKey(blank=True, help_text='Ej. Kg., m.,', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='utils.UnidadMedida', verbose_name='Unidad de Medida Elemental')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('cambio', models.FloatField(verbose_name='cambio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moneda', models.ForeignKey(default='USD', on_delete=django.db.models.deletion.PROTECT, related_name='cambios', to='utils.Moneda', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Tipo de Cambio',
                'verbose_name_plural': 'Tipos de Cambio',
                'ordering': ('-fecha',),
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos', verbose_name='Archivo')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ('id',),
            },
        ),
    ]
