# Generated by Django 2.2.12 on 2020-04-03 03:40

from django.db import migrations


def create_monedas(apps, schema_editor):
    Moneda = apps.get_model('utils', 'Moneda')
    monedas = (('Dólares Americanos', 'USD'), ('Guaraníes', 'PYG'))
    for m in monedas:
        Moneda.objects.create(nombre=m[0], codigo_iso=m[1])


def create_unidad_medidas(apps, schema_editor):
    UnidadMedida = apps.get_model('utils', 'UnidadMedida')
    unidades = (
        {'nombre': 'Unidad', 'abreviacion': 'u', 'acepta_decimales': False},
        {'nombre': 'Litro', 'abreviacion': 'L', 'acepta_decimales': True},
        {'nombre': 'Metro', 'abreviacion': 'm', 'acepta_decimales': True},
        {'nombre': 'Kilogramo', 'abreviacion': 'Kg', 'acepta_decimales': True}
    )
    for u in unidades:
        unid = UnidadMedida.objects.create(**u)


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_monedas, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_unidad_medidas, reverse_code=migrations.RunPython.noop),
    ]
