# Generated by Django 2.2.12 on 2020-04-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20200402_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmedida',
            name='abreviacion',
            field=models.CharField(blank=True, default='', help_text='Ej.: Kg. para Kilogramos.', max_length=10, verbose_name='Abreviación'),
        ),
    ]
