# Generated by Django 2.2.12 on 2020-04-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20200404_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocambio',
            name='moneda',
            field=models.CharField(choices=[('PYG', 'Guaraníes'), ('USD', 'Dólares')], default='PYG', max_length=3, verbose_name='Moneda'),
        ),
    ]
