# Generated by Django 2.2.12 on 2020-04-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_tipocambio_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocambio',
            name='moneda',
            field=models.CharField(choices=[('PYG', 'Guaraníes'), ('USD', 'Dólares')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterUniqueTogether(
            name='tipocambio',
            unique_together={('fecha', 'moneda')},
        ),
    ]
