# Generated by Django 2.2.12 on 2020-04-15 03:35

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_foto_galeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='archivo',
            field=models.ImageField(upload_to=utils.models.get_upload_path, verbose_name='Imagen'),
        ),
    ]
