# Generated by Django 2.2.12 on 2020-04-15 20:50

from django.db import migrations


def create_home_galery(apps, schema_editor):
    Galeria = apps.get_model('utils', 'Galeria')
    Galeria.objects.create(nombre='Pagina de Inicio')


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_auto_20200414_2335'),
    ]

    operations = [
        migrations.RunPython(create_home_galery, reverse_code=migrations.RunPython.noop)
    ]
